In [3]:
import pandas as pd

In [4]:
emp_dict = {
  'e_id': [1,2,3,4],
  'e_name':["A","B","C","D"],
  'e_salary': [10,20,15,30]
}

In [6]:
emp = pd.DataFrame(emp_dict)
emp

   e_id e_name  e_salary
0     1      A        10
1     2      B        20
2     3      C        15
3     4      D        30

In [7]:
emp.iloc[:,:]

   e_id e_name  e_salary
0     1      A        10
1     2      B        20
2     3      C        15
3     4      D        30

In [8]:
emp.iloc[:,:1]

   e_id
0     1
1     2
2     3
3     4

In [13]:
emp.iloc[:,:1]

   e_id
0     1
1     2
2     3
3     4

In [32]:
dataset = pd.read_csv('data.csv')

In [27]:
dataset

,age,gender,occupation,education_level,marital_status,income,credit_score,loan_status
0,32,NaN,Engineer,Bachelor's,Married,85000,720,Approved
1,45,Female,Teacher,Master's,Single,62000,680,Approved
2,28,Male,Student,High School,Single,25000,590,Denied
3,51,Female,Manager,Bachelor's,Married,105000,780,Approved
4,36,Male,Accountant,Bachelor's,Married,75000,710,Approved
...,...,...,...,...,...,...,...,...
56,39,Male,Architect,Master's,Married,100000,770,Approved
57,25,Female,Receptionist,High School,Single,32000,570,Denied
58,43,Male,Banker,Bachelor's,Married,95000,760,Approved
59,30,Female,Writer,Master's,Single,55000,650,Approved
60,38,Male,Chef,Associate's,Married,65000,700,Approved

In [28]:
dataset.head()

,age,gender,occupation,education_level,marital_status,income,credit_score,loan_status
0,32,NaN,Engineer,Bachelor's,Married,85000,720,Approved
1,45,Female,Teacher,Master's,Single,62000,680,Approved
2,28,Male,Student,High School,Single,25000,590,Denied
3,51,Female,Manager,Bachelor's,Married,105000,780,Approved
4,36,Male,Accountant,Bachelor's,Married,75000,710,Approved

In [23]:
dataset.tail()

,age,gender,occupation,education_level,marital_status,income,credit_score,loan_status
56,39,Male,Architect,Master's,Married,100000,770,Approved
57,25,Female,Receptionist,High School,Single,32000,570,Denied
58,43,Male,Banker,Bachelor's,Married,95000,760,Approved
59,30,Female,Writer,Master's,Single,55000,650,Approved
60,38,Male,Chef,Associate's,Married,65000,700,Approved

In [24]:
dataset.describe()

             age         income  credit_score
count  61.000000      61.000000     61.000000
mean   37.081967   78983.606557    709.836066
std     8.424755   33772.025802     72.674888
min    24.000000   25000.000000    560.000000
25%    30.000000   52000.000000    650.000000
50%    36.000000   78000.000000    720.000000
75%    43.000000   98000.000000    770.000000
max    55.000000  180000.000000    830.000000

In [30]:
dataset.isna().sum()

age                0
gender             1
occupation         0
education_level    0
marital_status     0
income             0
credit_score       0
loan_status        0
dtype: int64

In [33]:
dataset.duplicated().sum()

4