In [ ]:
import pandas as pd

In [15]:
data = pd.read_csv('orders.csv')
data

    OrderID Customer   Product     Category  Quantity    Price  Discount
0      1001    Alice    Laptop  Electronics       1.0  65000.0    5000.0
1      1002      Bob  Keyboard  Electronics       2.0   1500.0     100.0
2      1003  Charlie     Mouse  Electronics       3.0    700.0       NaN
3      1004    Alice   Monitor  Electronics       1.0  12000.0     500.0
4      1005    David     Chair    Furniture       2.0   4500.0     300.0
5      1006      Eve      Desk    Furniture       NaN   8000.0     500.0
6      1007    Frank    Laptop  Electronics       1.0  65000.0    5000.0
7      1008   George  Keyboard  Electronics       2.0   1500.0     100.0
8      1008   George  Keyboard  Electronics       2.0   1500.0     100.0
9      1009    Harry     Table    Furniture       1.0      NaN     250.0
10     1010      Ivy     Mouse  Electronics       4.0    700.0      50.0

In [10]:
data.isna().sum()

OrderID     0
Customer    0
Product     0
Category    0
Quantity    1
Price       1
Discount    1
dtype: int64

In [16]:
data['Quantity'] = data['Quantity'].fillna(1)

In [17]:
data

    OrderID Customer   Product     Category  Quantity    Price  Discount
0      1001    Alice    Laptop  Electronics       1.0  65000.0    5000.0
1      1002      Bob  Keyboard  Electronics       2.0   1500.0     100.0
2      1003  Charlie     Mouse  Electronics       3.0    700.0       NaN
3      1004    Alice   Monitor  Electronics       1.0  12000.0     500.0
4      1005    David     Chair    Furniture       2.0   4500.0     300.0
5      1006      Eve      Desk    Furniture       1.0   8000.0     500.0
6      1007    Frank    Laptop  Electronics       1.0  65000.0    5000.0
7      1008   George  Keyboard  Electronics       2.0   1500.0     100.0
8      1008   George  Keyboard  Electronics       2.0   1500.0     100.0
9      1009    Harry     Table    Furniture       1.0      NaN     250.0
10     1010      Ivy     Mouse  Electronics       4.0    700.0      50.0

In [20]:
data['Price'] = data['Price'].fillna(data['Price'].mean())

In [21]:
data

    OrderID Customer   Product     Category  Quantity    Price  Discount
0      1001    Alice    Laptop  Electronics       1.0  65000.0    5000.0
1      1002      Bob  Keyboard  Electronics       2.0   1500.0     100.0
2      1003  Charlie     Mouse  Electronics       3.0    700.0       NaN
3      1004    Alice   Monitor  Electronics       1.0  12000.0     500.0
4      1005    David     Chair    Furniture       2.0   4500.0     300.0
5      1006      Eve      Desk    Furniture       1.0   8000.0     500.0
6      1007    Frank    Laptop  Electronics       1.0  65000.0    5000.0
7      1008   George  Keyboard  Electronics       2.0   1500.0     100.0
8      1008   George  Keyboard  Electronics       2.0   1500.0     100.0
9      1009    Harry     Table    Furniture       1.0  16040.0     250.0
10     1010      Ivy     Mouse  Electronics       4.0    700.0      50.0

In [22]:
data['Discount'] = data['Discount'].fillna(50)

In [23]:
data

    OrderID Customer   Product     Category  Quantity    Price  Discount
0      1001    Alice    Laptop  Electronics       1.0  65000.0    5000.0
1      1002      Bob  Keyboard  Electronics       2.0   1500.0     100.0
2      1003  Charlie     Mouse  Electronics       3.0    700.0      50.0
3      1004    Alice   Monitor  Electronics       1.0  12000.0     500.0
4      1005    David     Chair    Furniture       2.0   4500.0     300.0
5      1006      Eve      Desk    Furniture       1.0   8000.0     500.0
6      1007    Frank    Laptop  Electronics       1.0  65000.0    5000.0
7      1008   George  Keyboard  Electronics       2.0   1500.0     100.0
8      1008   George  Keyboard  Electronics       2.0   1500.0     100.0
9      1009    Harry     Table    Furniture       1.0  16040.0     250.0
10     1010      Ivy     Mouse  Electronics       4.0    700.0      50.0

In [24]:
data.isna().sum()

OrderID     0
Customer    0
Product     0
Category    0
Quantity    0
Price       0
Discount    0
dtype: int64

In [26]:
data.duplicated().sum()

1

In [27]:
data.drop_duplicates()

    OrderID Customer   Product     Category  Quantity    Price  Discount
0      1001    Alice    Laptop  Electronics       1.0  65000.0    5000.0
1      1002      Bob  Keyboard  Electronics       2.0   1500.0     100.0
2      1003  Charlie     Mouse  Electronics       3.0    700.0      50.0
3      1004    Alice   Monitor  Electronics       1.0  12000.0     500.0
4      1005    David     Chair    Furniture       2.0   4500.0     300.0
5      1006      Eve      Desk    Furniture       1.0   8000.0     500.0
6      1007    Frank    Laptop  Electronics       1.0  65000.0    5000.0
7      1008   George  Keyboard  Electronics       2.0   1500.0     100.0
9      1009    Harry     Table    Furniture       1.0  16040.0     250.0
10     1010      Ivy     Mouse  Electronics       4.0    700.0      50.0

In [28]:
data['Total Price_BD'] = data['Quantity'] * data['Price']

In [29]:
data

,OrderID,Customer,Product,Category,Quantity,Price,Discount,Total Price_BD
0,1001,Alice,Laptop,Electronics,1.0,65000.0,5000.0,65000.0
1,1002,Bob,Keyboard,Electronics,2.0,1500.0,100.0,3000.0
2,1003,Charlie,Mouse,Electronics,3.0,700.0,50.0,2100.0
3,1004,Alice,Monitor,Electronics,1.0,12000.0,500.0,12000.0
4,1005,David,Chair,Furniture,2.0,4500.0,300.0,9000.0
5,1006,Eve,Desk,Furniture,1.0,8000.0,500.0,8000.0
6,1007,Frank,Laptop,Electronics,1.0,65000.0,5000.0,65000.0
7,1008,George,Keyboard,Electronics,2.0,1500.0,100.0,3000.0
8,1008,George,Keyboard,Electronics,2.0,1500.0,100.0,3000.0
9,1009,Harry,Table,Furniture,1.0,16040.0,250.0,16040.0
10,1010,Ivy,Mouse,Electronics,4.0,700.0,50.0,2800.0

In [30]:
data['Total Price'] = data['Total Price_BD'] - data['Discount']

In [31]:
data

,OrderID,Customer,Product,Category,Quantity,Price,Discount,Total Price_BD,Total Price
0,1001,Alice,Laptop,Electronics,1.0,65000.0,5000.0,65000.0,60000.0
1,1002,Bob,Keyboard,Electronics,2.0,1500.0,100.0,3000.0,2900.0
2,1003,Charlie,Mouse,Electronics,3.0,700.0,50.0,2100.0,2050.0
3,1004,Alice,Monitor,Electronics,1.0,12000.0,500.0,12000.0,11500.0
4,1005,David,Chair,Furniture,2.0,4500.0,300.0,9000.0,8700.0
5,1006,Eve,Desk,Furniture,1.0,8000.0,500.0,8000.0,7500.0
6,1007,Frank,Laptop,Electronics,1.0,65000.0,5000.0,65000.0,60000.0
7,1008,George,Keyboard,Electronics,2.0,1500.0,100.0,3000.0,2900.0
8,1008,George,Keyboard,Electronics,2.0,1500.0,100.0,3000.0,2900.0
9,1009,Harry,Table,Furniture,1.0,16040.0,250.0,16040.0,15790.0
10,1010,Ivy,Mouse,Electronics,4.0,700.0,50.0,2800.0,2750.0

In [33]:
data.to_csv('processed_orders.csv')